name: Build Resume

on:
  push:
    paths:
      - 'cv/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'cv/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Install fonts
      run: |
        apt-get update -qq
        apt-get install -qq --yes \
          fonts-roboto \
          fonts-adobe-sourcesans3 \
          > /dev/null
        luaotfload-tool --update --quiet

    - name: Compile resume
      run: TEXINPUTS="./vendor/awesome-cv//:" lualatex resume.tex
      working-directory: cv

    - name: Rename PDF for download
      run: cp cv/resume.pdf 'cv/Caleb Mennen Resume.pdf'

    - name: Upload PDF
      uses: actions/upload-artifact@v6
      with:
        name: resume
        path: cv/Caleb Mennen Resume.pdf

    - name: Update latest release
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Resume
        body: Automatically updated on every push to master.
        files: cv/Caleb Mennen Resume.pdf
        make_latest: true
        prerelease: false

    - name: Create tagged release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: cv/Caleb Mennen Resume.pdf
